const fs = require("fs");
const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, PageBreak, ShadingType,
  WidthType, TableOfContents, Header, Footer, PageNumber,
  convertInchesToTwip,
} = require("docx");

// ── Helpers ──
function p(text, options = {}) {
  return new Paragraph({
    spacing: { after: 120, line: 360 },
    ...options,
    children: [
      new TextRun({ text, font: "Times New Roman", size: options.fontSize || 26, bold: options.bold || false, italics: options.italics || false, color: "000000", ...options.runOptions }),
    ],
  });
}

function heading(text, level) {
  return new Paragraph({
    heading: level,
    alignment: level === HeadingLevel.HEADING_1 ? AlignmentType.CENTER : AlignmentType.LEFT,
    spacing: { before: level === HeadingLevel.HEADING_1 ? 360 : 240, after: 180 },
    children: [new TextRun({ text, font: "Times New Roman", size: level === HeadingLevel.HEADING_1 ? 32 : level === HeadingLevel.HEADING_2 ? 28 : 26, bold: true, color: "000000" })],
  });
}

function emptyLine() { return new Paragraph({ spacing: { after: 0 }, children: [] }); }

function bulletPoint(text, level = 0) {
  return new Paragraph({
    spacing: { after: 60, line: 360 },
    indent: { left: convertInchesToTwip(0.5 + level * 0.3) },
    children: [
      new TextRun({ text: "• ", font: "Times New Roman", size: 26, color: "000000" }),
      new TextRun({ text, font: "Times New Roman", size: 26, color: "000000" }),
    ],
  });
}

function numberedPoint(num, text, indent = 0) {
  return new Paragraph({
    spacing: { after: 60, line: 360 },
    indent: { left: convertInchesToTwip(0.5 + indent * 0.3) },
    children: [
      new TextRun({ text: `${num}. `, font: "Times New Roman", size: 26, bold: true, color: "000000" }),
      new TextRun({ text, font: "Times New Roman", size: 26, color: "000000" }),
    ],
  });
}

function toc() {
  return new TableOfContents("Mục lục", {
    hyperlink: true,
    headingStyleRange: "1-3",
    stylesWithLevels: [
      { level: 1, style: "Heading 1" }, { level: 2, style: "Heading 2" }, { level: 3, style: "Heading 3" },
    ],
  });
}

function createTable(headers, rows) {
  const allRows = [
    new TableRow({ tableHeader: true, children: headers.map(h => new TableCell({ shading: { type: ShadingType.SOLID, color: "2E4057", fill: "2E4057" }, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: h, font: "Times New Roman", size: 22, bold: true, color: "FFFFFF" })] })] })) }),
    ...rows.map(row => new TableRow({ children: row.map(cell => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: String(cell), font: "Times New Roman", size: 22, color: "000000" })] })] })) })),
  ];
  return new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: allRows });
}

function pageBreak() { return new Paragraph({ children: [new PageBreak()] }); }

// ==================== BUILD DOCUMENT ====================
const doc = new Document({
  styles: { default: { document: { run: { font: "Times New Roman", size: 26 } } } },
  sections: [
    // ─── TITLE PAGE ───
    {
      properties: { page: { margin: { top: 720, bottom: 720, left: 720, right: 720 } } },
      children: [
        emptyLine(), emptyLine(), emptyLine(), emptyLine(),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 }, children: [new TextRun({ text: "BÁO CÁO CUỐI KHÓA", font: "Times New Roman", size: 36, bold: true, color: "000000" })] }),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 80 }, children: [new TextRun({ text: "MÔN: CÔNG NGHỆ BLOCKCHAIN &", font: "Times New Roman", size: 28, bold: true, color: "000000" })] }),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 100 }, children: [new TextRun({ text: "THÀNH PHỐ THÔNG MINH - NÔNG NGHIỆP THÔNG MINH", font: "Times New Roman", size: 28, bold: true, color: "000000" })] }),
        emptyLine(), emptyLine(),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 }, children: [new TextRun({ text: "ĐỀ TÀI:", font: "Times New Roman", size: 26, italics: true, color: "000000" })] }),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 80 }, children: [new TextRun({ text: "HỆ THỐNG MÁY BÁN HÀNG TỰ ĐỘNG THÔNG MINH", font: "Times New Roman", size: 34, bold: true, color: "1F4E79" })] }),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 80 }, children: [new TextRun({ text: "TÍCH HỢP BLOCKCHAIN VÀ IoT", font: "Times New Roman", size: 34, bold: true, color: "1F4E79" })] }),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 80 }, children: [new TextRun({ text: "ỨNG DỤNG TRONG THÀNH PHỐ THÔNG MINH", font: "Times New Roman", size: 30, bold: true, color: "2E7D32" })] }),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 100 }, children: [new TextRun({ text: "VÀ NÔNG NGHIỆP THÔNG MINH", font: "Times New Roman", size: 30, bold: true, color: "2E7D32" })] }),
        emptyLine(), emptyLine(), emptyLine(),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 80 }, children: [new TextRun({ text: "Giảng viên hướng dẫn: TS. Nguyễn Văn A", font: "Times New Roman", size: 26, color: "000000" })] }),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 }, children: [new TextRun({ text: "Sinh viên thực hiện:", font: "Times New Roman", size: 26, color: "000000" })] }),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 60 }, children: [new TextRun({ text: "Họ và tên - MSSV", font: "Times New Roman", size: 26, color: "000000" })] }),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 }, children: [new TextRun({ text: "Lớp: Công nghệ Blockchain", font: "Times New Roman", size: 26, color: "000000" })] }),
        emptyLine(), emptyLine(),
        new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Hà Nội, tháng 6 năm 2026", font: "Times New Roman", size: 26, bold: true, color: "000000" })] }),
      ],
    },
    // ─── MAIN CONTENT ───
    {
      properties: { page: { margin: { top: 720, bottom: 720, left: 1080, right: 720 } } },
      headers: { default: new Header({ children: [new Paragraph({ alignment: AlignmentType.RIGHT, children: [new TextRun({ text: "Máy bán hàng thông minh: Blockchain, IoT, Thành phố & Nông nghiệp thông minh", font: "Times New Roman", size: 18, italics: true, color: "888888" })] })] }) },
      footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Trang ", font: "Times New Roman", size: 18, color: "000000" }), new TextRun({ children: [PageNumber.CURRENT], font: "Times New Roman", size: 18, color: "000000" })] })] }) },
      children: [

        // ── ACKNOWLEDGEMENTS ──
        heading("LỜI CẢM ƠN", HeadingLevel.HEADING_1),
        emptyLine(),
        p("Em xin gửi lời cảm ơn chân thành đến các thầy cô trong bộ môn Công nghệ Thông tin, đặc biệt là thầy TS. Nguyễn Văn A - người đã trực tiếp hướng dẫn, định hướng và góp ý quý báu trong suốt quá trình thực hiện đề tài."),
        p("Đề tài này là sự kết hợp kiến thức từ hai môn học quan trọng: Công nghệ Blockchain và Thành phố thông minh - Nông nghiệp thông minh. Những kiến thức nền tảng về chuỗi khối, hợp đồng thông minh, IoT, kiến trúc đô thị thông minh và nông nghiệp công nghệ cao đã giúp nhóm có cái nhìn toàn diện để xây dựng một hệ thống có tính ứng dụng thực tiễn cao."),
        p("Em cũng xin cảm ơn các bạn trong nhóm đã cùng nhau nỗ lực, hợp tác và chia sẻ kiến thức để hoàn thành hệ thống này. Sự kết hợp giữa các thành viên với các thế mạnh khác nhau về phát triển ứng dụng di động, lập trình nhúng IoT, công nghệ blockchain, và tư duy quy hoạch đô thị - nông nghiệp đã giúp dự án được triển khai một cách toàn diện."),
        p("Xin trân trọng cảm ơn!"),

        // ── ABSTRACT ──
        pageBreak(),
        heading("TÓM TẮT ĐỀ TÀI", HeadingLevel.HEADING_1),
        emptyLine(),
        p("Hệ thống máy bán hàng tự động thông minh tích hợp Blockchain và IoT là một giải pháp công nghệ đa lĩnh vực, kết hợp ba trụ cột: Blockchain (chuỗi khối) cho thanh toán minh bạch, Internet of Things (IoT) cho điều khiển phần cứng thông minh, và Ứng dụng Di động cho trải nghiệm người dùng. Hệ thống được thiết kế để phục vụ hai bối cảnh ứng dụng chiến lược: Thành phố thông minh (Smart City) và Nông nghiệp thông minh (Smart Agriculture)."),
        p("Trong bối cảnh Thành phố thông minh, hệ thống đóng vai trò như một điểm bán lẻ tự động thông minh trong hạ tầng đô thị. Người dân có thể định vị máy bán hàng gần nhất qua GPS, tham gia hàng đợi ảo, thanh toán không tiền mặt bằng tiền mã hóa, và nhận sản phẩm một cách tự động. Hệ thống góp phần xây dựng một đô thị văn minh, hiện đại với các dịch vụ công cộng thông minh, giảm thời gian chờ đợi và tối ưu hóa trải nghiệm người dùng."),
        p("Trong bối cảnh Nông nghiệp thông minh, hệ thống hoạt động như một kênh phân phối trực tiếp từ nông trại đến người tiêu dùng (Farm-to-Consumer). Nhờ công nghệ blockchain, mỗi sản phẩm nông nghiệp đều có thể được truy xuất nguồn gốc minh bạch - từ khâu gieo trồng, chăm sóc, thu hoạch đến khi đến tay người tiêu dùng. Điều này giúp loại bỏ các khâu trung gian, giảm chi phí, tăng thu nhập cho nông dân, và đảm bảo an toàn thực phẩm cho người tiêu dùng."),
        p("Về mặt kỹ thuật, hệ thống sử dụng mạng Ethereum Sepolia cho thanh toán, ESP32 cho điều khiển phần cứng với 4 khe sản phẩm, màn hình TFT, cảm biến hồng ngoại, và ứng dụng Flutter cho giao diện người dùng. Backend Node.js với Firebase Firestore quản lý dữ liệu và Socket.io cung cấp giao tiếp thời gian thực."),
        emptyLine(),
        p("Từ khóa: Blockchain, IoT, ESP32, Flutter, Máy bán hàng tự động, Thành phố thông minh, Nông nghiệp thông minh, Truy xuất nguồn gốc, Thanh toán phi tập trung, Farm-to-Consumer", { italics: true }),

        // ── TABLE OF CONTENTS ──
        pageBreak(),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 360 }, children: [new TextRun({ text: "MỤC LỤC", font: "Times New Roman", size: 32, bold: true, color: "000000" })] }),
        emptyLine(), toc(), emptyLine(),
        p("Lưu ý: Nhấn chuột phải vào mục lục và chọn \"Cập nhật trường\" (Update Field) để hiển thị số trang chính xác.", { italics: true, fontSize: 20, runOptions: { color: "888888" } }),

        // ═══════ CHAPTER 1: INTRODUCTION ═══════
        pageBreak(),
        heading("CHƯƠNG 1: TỔNG QUAN ĐỀ TÀI", HeadingLevel.HEADING_1),
        emptyLine(),
        heading("1.1 Đặt vấn đề", HeadingLevel.HEADING_2),

        heading("1.1.1 Bối cảnh Cuộc cách mạng Công nghiệp 4.0", HeadingLevel.HEADING_3),
        p("Thế giới đang bước vào kỷ nguyên của Cuộc cách mạng Công nghiệp 4.0, nơi ranh giới giữa thế giới vật lý, kỹ thuật số và sinh học ngày càng mờ nhạt. Các công nghệ tiên tiến như Blockchain, Internet of Things (IoT), Trí tuệ Nhân tạo (AI), Dữ liệu lớn (Big Data) và Điện toán đám mây (Cloud Computing) đang hội tụ, tạo ra những thay đổi sâu sắc trong mọi lĩnh vực của đời sống kinh tế - xã hội."),
        p("Hai xu hướng nổi bật trong làn sóng công nghệ này là Thành phố thông minh (Smart City) và Nông nghiệp thông minh (Smart Agriculture). Đây là những lĩnh vực được Chính phủ Việt Nam đặc biệt quan tâm, thể hiện qua Đề án phát triển đô thị thông minh bền vững và Chương trình chuyển đổi số trong nông nghiệp."),

        heading("1.1.2 Thực trạng máy bán hàng tự động tại Việt Nam", HeadingLevel.HEADING_3),
        p("Máy bán hàng tự động đã xuất hiện tại Việt Nam từ những năm 2010 và ngày càng phổ biến tại các thành phố lớn như Hà Nội, TP. Hồ Chí Minh, Đà Nẵng. Tuy nhiên, các hệ thống hiện tại vẫn tồn tại nhiều hạn chế:"),
        numberedPoint(1, "Thiếu minh bạch trong giao dịch: Người dùng không thể xác minh độc lập giao dịch. Mọi thông tin do nhà vận hành kiểm soát."),
        numberedPoint(2, "Hạn chế về phương thức thanh toán: Chủ yếu dùng tiền mặt hoặc thẻ ngân hàng, chưa hỗ trợ thanh toán số hiện đại."),
        numberedPoint(3, "Không có khả năng truy xuất nguồn gốc: Người tiêu dùng không biết sản phẩm đến từ đâu, được sản xuất như thế nào."),
        numberedPoint(4, "Quản lý hàng đợi thủ công: Tại các điểm đông người, việc xếp hàng gây lãng phí thời gian."),
        numberedPoint(5, "Thiếu kết nối với hạ tầng đô thị thông minh: Các máy hoạt động độc lập, không tích hợp vào hệ sinh thái thành phố thông minh."),

        heading("1.1.3 Giải pháp đề xuất", HeadingLevel.HEADING_3),
        p("Nhóm đề xuất xây dựng Hệ thống máy bán hàng tự động thông minh tích hợp Blockchain và IoT, hướng đến hai mục tiêu chiến lược:"),
        emptyLine(),
        p("Mục tiêu 1 - Phục vụ Thành phố thông minh:", { bold: true }),
        bulletPoint("Tạo ra điểm bán lẻ tự động thông minh trong hạ tầng đô thị"),
        bulletPoint("Tích hợp GPS giúp người dân tìm máy gần nhất trong bán kính 50m"),
        bulletPoint("Hàng đợi ảo giảm ùn tắc tại điểm bán, tối ưu thời gian chờ đợi"),
        bulletPoint("Thanh toán không tiền mặt qua blockchain, hướng tới xã hội không tiền mặt"),
        bulletPoint("Dữ liệu giao dịch công khai phục vụ công tác quy hoạch đô thị"),
        emptyLine(),
        p("Mục tiêu 2 - Phục vụ Nông nghiệp thông minh:", { bold: true }),
        bulletPoint("Kênh phân phối trực tiếp nông sản từ nông trại đến người tiêu dùng (Farm-to-Consumer)"),
        bulletPoint("Truy xuất nguồn gốc sản phẩm minh bạch qua blockchain"),
        bulletPoint("Giảm khâu trung gian, tăng thu nhập cho nông dân"),
        bulletPoint("Đảm bảo an toàn thực phẩm, chống hàng giả, hàng kém chất lượng"),
        bulletPoint("Hỗ trợ tiêu thụ nông sản địa phương, phát triển kinh tế nông thôn"),

        heading("1.2 Mục tiêu đề tài", HeadingLevel.HEADING_2),
        heading("1.2.1 Mục tiêu chung", HeadingLevel.HEADING_3),
        p("Xây dựng thành công một hệ thống máy bán hàng tự động hoàn chỉnh, tích hợp công nghệ Blockchain cho thanh toán minh bạch và truy xuất nguồn gốc, công nghệ IoT cho điều khiển phần cứng, ứng dụng trong bối cảnh Thành phố thông minh và Nông nghiệp thông minh."),
        heading("1.2.2 Mục tiêu cụ thể", HeadingLevel.HEADING_3),
        numberedPoint(1, "Thiết kế lớp thanh toán Blockchain minh bạch, chống gian lận, ghi nhận giao dịch vĩnh viễn"),
        numberedPoint(2, "Xây dựng hệ thống IoT với ESP32 điều khiển 4 khe sản phẩm, màn hình TFT, cảm biến IR"),
        numberedPoint(3, "Phát triển ứng dụng Flutter với đăng nhập Web3, GPS, hàng đợi ảo, WebSocket"),
        numberedPoint(4, "Tích hợp tính năng truy xuất nguồn gốc nông sản qua blockchain"),
        numberedPoint(5, "Thiết kế mô hình kết nối với hạ tầng thành phố thông minh"),
        numberedPoint(6, "Xây dựng backend quản lý tập trung với Firestore và Socket.io"),

        heading("1.3 Phạm vi và giới hạn", HeadingLevel.HEADING_2),
        p("Phạm vi:", { bold: true }),
        bulletPoint("Blockchain: Mạng thử nghiệm Ethereum Sepolia, giá 0.001 ETH/sản phẩm"),
        bulletPoint("Phần cứng: ESP32 với 4 khe sản phẩm, màn hình TFT 240×320"),
        bulletPoint("Mobile: Flutter đa nền tảng, Web3Auth (Google), GPS, WebSocket"),
        bulletPoint("Ứng dụng: Mô hình điểm bán lẻ đô thị + kênh phân phối nông sản"),
        emptyLine(),
        p("Giới hạn:", { bold: true }),
        bulletPoint("Sử dụng testnet, chưa triển khai trên mainnet"),
        bulletPoint("Chưa có smart contract tùy chỉnh cho truy xuất nguồn gốc phức tạp"),
        bulletPoint("Phần cứng là phiên bản thử nghiệm, chưa đạt chuẩn thương mại"),
        bulletPoint("Mô hình thành phố thông minh ở quy mô nhỏ (một máy)"),

        heading("1.4 Bố cục báo cáo", HeadingLevel.HEADING_2),
        p("Báo cáo được tổ chức thành 6 chương:"),
        bulletPoint("Chương 1: Tổng quan đề tài"),
        bulletPoint("Chương 2: Cơ sở lý thuyết (Blockchain, IoT, Thành phố thông minh, Nông nghiệp thông minh)"),
        bulletPoint("Chương 3: Kiến trúc hệ thống (5 lớp: Hardware, Firmware, Backend, Blockchain, Mobile)"),
        bulletPoint("Chương 4: Ứng dụng trong Thành phố thông minh"),
        bulletPoint("Chương 5: Ứng dụng trong Nông nghiệp thông minh"),
        bulletPoint("Chương 6: Kết luận và hướng phát triển"),

        // ═══════ CHAPTER 2: THEORETICAL FOUNDATION ═══════
        pageBreak(),
        heading("CHƯƠNG 2: CƠ SỞ LÝ THUYẾT", HeadingLevel.HEADING_1),
        emptyLine(),
        heading("2.1 Công nghệ Blockchain", HeadingLevel.HEADING_2),
        heading("2.1.1 Khái niệm cơ bản", HeadingLevel.HEADING_3),
        p("Blockchain (chuỗi khối) là công nghệ sổ cái phân tán (Distributed Ledger Technology - DLT), trong đó dữ liệu được lưu trữ trong các khối (block) liên kết với nhau bằng mật mã. Mỗi khối chứa: mã băm của khối trước, dấu thời gian, cây Merkle của các giao dịch, và nonce. Cấu trúc này tạo nên bốn đặc tính cốt lõi: phi tập trung, minh bạch, bất biến và bảo mật."),

        heading("2.1.2 Ethereum và Hợp đồng thông minh", HeadingLevel.HEADING_3),
        p("Ethereum là nền tảng blockchain thế hệ thứ hai, cho phép thực thi Smart Contract trên Ethereum Virtual Machine (EVM). Smart Contract là chương trình tự động thực thi theo nguyên lý \"if-this-then-that\", được triển khai trên blockchain và không thể thay đổi sau khi deploy."),
        p("Trong hệ thống này, Ethereum Sepolia Testnet (Chain ID: 11155111) được sử dụng để xử lý thanh toán. Mỗi giao dịch mua hàng là một giao dịch ETH từ ví người dùng đến ví máy bán hàng. Backend xác minh giao dịch qua 5 bước: kiểm tra tồn tại, chain ID, địa chỉ nhận, số tiền, và trạng thái xác nhận. Cơ chế này đảm bảo mọi giao dịch được ghi nhận công khai, không thể thay đổi, chống gian lận hiệu quả."),

        heading("2.1.3 Ứng dụng Blockchain trong truy xuất nguồn gốc", HeadingLevel.HEADING_3),
        p("Một trong những ứng dụng quan trọng của blockchain là truy xuất nguồn gốc sản phẩm. Mỗi bước trong chuỗi cung ứng (sản xuất, chế biến, vận chuyển, phân phối) được ghi lại trên blockchain dưới dạng một giao dịch. Người tiêu dùng có thể quét mã QR để xem toàn bộ hành trình của sản phẩm."),
        p("Trong bối cảnh nông nghiệp thông minh, blockchain cung cấp:"),
        bulletPoint("Hồ sơ số không thể thay đổi cho mỗi lô nông sản"),
        bulletPoint("Thông tin về nguồn gốc, phương pháp canh tác, chứng nhận hữu cơ"),
        bulletPoint("Lịch sử vận chuyển và bảo quản (nhiệt độ, độ ẩm)"),
        bulletPoint("Xác thực sản phẩm chính hiệu, chống hàng giả"),

        heading("2.1.4 Blockchain trong hệ thống thanh toán máy bán hàng", HeadingLevel.HEADING_3),
        p("Trong hệ thống máy bán hàng, Blockchain được sử dụng như một lớp xử lý thanh toán phi tập trung thông qua cơ chế xác minh giao dịch (transaction verification). Đây là ứng dụng cốt lõi của công nghệ blockchain trong hệ thống. Cụ thể:"),
        p("Kiến trúc thanh toán Blockchain:", { bold: true }),
        bulletPoint("Mạng lưới: Ethereum Sepolia Testnet (Chain ID: 11155111)"),
        bulletPoint("Đồng tiền: ETH (Ether) - đồng tiền gốc của mạng Ethereum"),
        bulletPoint("Ví nhận thanh toán: 0x94988621cDd1aCEAa0284f65cb2EBE0B40AD7c85"),
        bulletPoint("Giá sản phẩm: 0.001 ETH (~2-3 USD tại thời điểm phát triển)"),
        bulletPoint("Gas fee: Người dùng trả phí gas (~21,000 gas × ~1 Gwei = 0.000021 ETH)"),
        bulletPoint("Thời gian xác nhận: 12-20 giây cho 1 block confirmation"),
        emptyLine(),
        p("Cơ chế xác minh giao dịch 5 bước (Blockchain Transaction Verification):", { bold: true }),
        p("Backend sử dụng thư viện Ethers.js v6 để xác minh mỗi giao dịch thanh toán qua 5 bước kiểm tra nghiêm ngặt:"),
        emptyLine(),
        p("Bước 1 - Kiểm tra sự tồn tại của giao dịch trên chuỗi khối:", { bold: true }),
        p("Backend gọi provider.getTransaction(txHash) để truy vấn thông tin giao dịch từ mạng Sepolia. Nếu giao dịch không tồn tại (tx = null), hệ thống trả về lỗi \"Transaction not found on chain\". Bước này đảm bảo txHash là hợp lệ và giao dịch đã được phát tán lên mạng lưới Ethereum. Đây là lớp bảo vệ đầu tiên chống lại việc gửi txHash giả mạo."),
        emptyLine(),
        p("Bước 2 - Xác minh Chain ID (Mạng lưới):", { bold: true }),
        p("Hệ thống kiểm tra tx.chainId === 11155111 (Sepolia Testnet). Nếu chain ID không khớp, giao dịch bị từ chối với lỗi \"Wrong chain\". Cơ chế này ngăn chặn tấn công replay attack - kẻ tấn công không thể sao chép một giao dịch từ mạng khác (như Mainnet, Goerli) và phát lại trên Sepolia. Đây là một tính năng bảo mật quan trọng được tích hợp sẵn trong giao thức Ethereum (EIP-155)."),
        emptyLine(),
        p("Bước 3 - Xác minh địa chỉ người nhận:", { bold: true }),
        p("Hệ thống so sánh tx.to (địa chỉ nhận trong giao dịch) với VENDING_WALLET_ADDRESS đã cấu hình. Nếu không khớp, giao dịch bị từ chối. Bước này đảm bảo ETH được gửi đến đúng ví của máy bán hàng, không phải một địa chỉ ví khác. Địa chỉ ví được lưu trong biến môi trường và có thể thay đổi khi triển khai máy mới."),
        emptyLine(),
        p("Bước 4 - Xác minh số tiền thanh toán:", { bold: true }),
        p("Hệ thống so sánh tx.value với PRODUCT_PRICE_ETH (0.001 ETH). Sử dụng ethers.parseEther() để chuyển đổi ETH sang Wei (1 ETH = 10¹⁸ Wei) và so sánh bằng BigInt để tránh sai số dấu phẩy động. Nếu tx.value < expectedWei, giao dịch bị từ chối với lỗi \"Insufficient amount\". Cơ chế này đảm bảo người dùng thanh toán đúng số tiền, không thể mua hàng với giá thấp hơn quy định."),
        emptyLine(),
        p("Bước 5 - Chờ xác nhận khối (Block Confirmation):", { bold: true }),
        p("Giao dịch Ethereum cần được validator đưa vào một khối và khối đó được thêm vào chuỗi. Backend poll receipt mỗi 3 giây trong tối đa 60 giây (20 lần × 3s). Nếu sau 60 giây không có receipt → lỗi \"Transaction not confirmed after 60s\". Nếu receipt.status === 0 → giao dịch đã bị revert (thất bại). Chỉ khi receipt.status === 1, giao dịch mới được coi là thành công. Bước này đảm bảo giao dịch đã được xác nhận vĩnh viễn trên blockchain trước khi phân phối sản phẩm."),
        emptyLine(),
        p("Sau khi vượt qua cả 5 bước, backend trả về kết quả xác minh thành công với các thông tin: địa chỉ người gửi (from), địa chỉ người nhận (to), số ETH (amountETH), số khối (blockNumber), số lần xác nhận (confirmations). Những thông tin này được lưu vĩnh viễn trong Firestore và có thể đối chiếu với blockchain bất kỳ lúc nào."),
        emptyLine(),
        p("Xử lý các trường hợp lỗi:", { bold: true }),
        createTable(
          ["Trường hợp lỗi", "Cách phát hiện", "Thông báo cho người dùng", "Cơ chế bảo vệ"],
          [
            ["txHash không tồn tại", "getTransaction() → null", "\"Transaction not found on chain\"", "Chống gửi mã giả"],
            ["Sai mạng (Chain ID)", "tx.chainId !== 11155111", "\"Wrong chain: expected 11155111\"", "Chống Replay Attack (EIP-155)"],
            ["Sai địa chỉ nhận", "tx.to !== VENDING_WALLET", "\"Wrong recipient\"", "Chống chuyển nhầm ví"],
            ["Thiếu tiền", "tx.value < expectedWei", "\"Insufficient amount\"", "Chống thanh toán thiếu"],
            ["Chưa xác nhận", "Không có receipt sau 60s", "\"Not confirmed after 60s\"", "Chống giao dịch treo"],
            ["Giao dịch revert", "receipt.status === 0", "\"Transaction reverted on chain\"", "Chống giao dịch lỗi"],
            ["Sai người gửi", "verification.from !== wallet", "\"Sender mismatch\"", "Chống dùng txHash của người khác"],
          ]
        ),

        heading("2.1.5 Ví tiền mã hóa và xác thực người dùng Web3", HeadingLevel.HEADING_3),
        p("Hệ thống sử dụng Web3Auth - một giải pháp xác thực Web3 tiên tiến, cho phép người dùng đăng nhập bằng tài khoản Google quen thuộc và tự động nhận được ví Ethereum. Cơ chế hoạt động:"),
        numberedPoint(1, "Người dùng đăng nhập Google → Web3Auth SDK tạo ví MPC (Multi-Party Computation)"),
        numberedPoint(2, "Private key được chia thành 3 phần (shares): thiết bị người dùng, Web3Auth Auth Network, yếu tố khôi phục"),
        numberedPoint(3, "Khi ký giao dịch: các bên MPC cùng tính chữ ký mà không cần tái tạo khóa đầy đủ"),
        numberedPoint(4, "App lấy private key → khởi tạo WalletService với web3dart"),
        numberedPoint(5, "Xác thực với backend qua EIP-191: ký nonce bằng private key → backend xác minh bằng ethers.verifyMessage()"),
        emptyLine(),
        p("Cơ chế này mang lại trải nghiệm người dùng liền mạch: không cần nhớ seed phrase, không cần cài extension ví, chỉ cần tài khoản Google. Đây là bước đột phá trong việc phổ cập công nghệ blockchain đến người dùng phổ thông - những người không có kiến thức chuyên sâu về crypto."),

        heading("2.1.6 Tính bất biến và minh bạch của giao dịch", HeadingLevel.HEADING_3),
        p("Một trong những ưu điểm quan trọng nhất của blockchain trong hệ thống là tính bất biến (immutability) và minh bạch (transparency) của dữ liệu giao dịch:"),
        bulletPoint("Mỗi giao dịch mua hàng được ghi vĩnh viễn trên blockchain → không ai có thể sửa, xóa sau khi đã xác nhận"),
        bulletPoint("Bất kỳ ai cũng có thể kiểm tra giao dịch trên Etherscan (https://sepolia.etherscan.io/) với txHash"),
        bulletPoint("Nhà vận hành không thể gian lận doanh thu vì mọi giao dịch đều công khai trên chuỗi khối"),
        bulletPoint("Người dùng có bằng chứng không thể chối cãi về việc đã thanh toán"),
        bulletPoint("Cơ quan thuế và kiểm toán có thể đối chiếu doanh thu trực tiếp từ blockchain, không phụ thuộc vào báo cáo của nhà vận hành"),
        bulletPoint("Trong tranh chấp: txHash là bằng chứng không thể bác bỏ, có giá trị pháp lý tiềm năng"),

        heading("2.2 Công nghệ IoT trong Thành phố và Nông nghiệp thông minh", HeadingLevel.HEADING_2),
        heading("2.2.1 Tổng quan về IoT", HeadingLevel.HEADING_3),
        p("Internet of Things (IoT) là mạng lưới các thiết bị vật lý được nhúng cảm biến, phần mềm và kết nối mạng để thu thập và trao đổi dữ liệu. Kiến trúc IoT 4 lớp bao gồm: lớp cảm biến (cảm biến, vi điều khiển), lớp mạng (WiFi, 5G, LoRa), lớp xử lý (Cloud, Edge Computing), và lớp ứng dụng (Dashboard, Mobile App)."),

        heading("2.2.2 ESP32 - Vi điều khiển cho IoT", HeadingLevel.HEADING_3),
        p("ESP32 là System-on-Chip của Espressif, với CPU Xtensa LX6 dual-core 240MHz, 520KB SRAM, WiFi 802.11 b/g/n, Bluetooth 4.2, và 34 chân GPIO. ESP32 được lựa chọn cho hệ thống vì: hỗ trợ WiFi AP+STA đồng thời, đủ mạnh để xử lý đồ họa TFT, thư viện Arduino phong phú, và giá thành hợp lý cho triển khai quy mô lớn."),

        heading("2.3 Thành phố thông minh (Smart City)", HeadingLevel.HEADING_2),
        heading("2.3.1 Khái niệm Thành phố thông minh", HeadingLevel.HEADING_3),
        p("Thành phố thông minh là mô hình đô thị ứng dụng công nghệ thông tin và truyền thông (ICT) để nâng cao chất lượng sống của người dân, tối ưu hóa hiệu quả vận hành đô thị, và phát triển bền vững. Theo ISO 37122:2019, thành phố thông minh được đánh giá qua 6 trụ cột: Kinh tế thông minh, Di chuyển thông minh, Môi trường thông minh, Con người thông minh, Cuộc sống thông minh, và Quản trị thông minh."),

        heading("2.3.2 Các thành phần của Thành phố thông minh", HeadingLevel.HEADING_3),
        p("Một thành phố thông minh điển hình bao gồm các thành phần:"),
        bulletPoint("Hạ tầng kết nối: Mạng 5G, WiFi công cộng, cảm biến IoT khắp đô thị"),
        bulletPoint("Giao thông thông minh: Đèn tín hiệu thích ứng, bãi đỗ xe tự động, xe buýt điện"),
        bulletPoint("Dịch vụ công trực tuyến: Chính phủ điện tử, thanh toán không tiền mặt"),
        bulletPoint("Quản lý năng lượng: Lưới điện thông minh, đèn đường LED tiết kiệm, năng lượng tái tạo"),
        bulletPoint("Quản lý chất thải: Thùng rác thông minh báo đầy, phân loại rác tự động"),
        bulletPoint("Bán lẻ thông minh: Cửa hàng không người bán, máy bán hàng tự động kết nối IoT"),

        heading("2.3.3 Vai trò của máy bán hàng thông minh trong Thành phố thông minh", HeadingLevel.HEADING_3),
        p("Máy bán hàng tự động thông minh là một mắt xích quan trọng trong hệ sinh thái bán lẻ của thành phố thông minh:"),
        bulletPoint("Điểm bán lẻ tự động 24/7, không cần nhân viên, giảm chi phí vận hành"),
        bulletPoint("Tích hợp với hệ thống thanh toán số của thành phố (không tiền mặt)"),
        bulletPoint("Cảm biến IoT báo cáo tồn kho theo thời gian thực, tối ưu chuỗi cung ứng"),
        bulletPoint("Dữ liệu tiêu dùng giúp chính quyền quy hoạch điểm bán lẻ hợp lý"),
        bulletPoint("Giảm ùn tắc giao thông: người dân mua sắm gần nhà thay vì đến siêu thị xa"),

        heading("2.4 Nông nghiệp thông minh (Smart Agriculture)", HeadingLevel.HEADING_2),
        heading("2.4.1 Khái niệm Nông nghiệp thông minh", HeadingLevel.HEADING_3),
        p("Nông nghiệp thông minh (Smart Agriculture) là việc ứng dụng công nghệ ICT, IoT, AI, Big Data và Blockchain vào sản xuất nông nghiệp nhằm tăng năng suất, chất lượng, hiệu quả kinh tế và phát triển bền vững. Các trụ cột chính bao gồm:"),
        bulletPoint("Nông nghiệp chính xác (Precision Agriculture): Sử dụng cảm biến, drone, GPS để tối ưu từng mét vuông canh tác"),
        bulletPoint("Nhà kính thông minh: Tự động điều khiển nhiệt độ, độ ẩm, ánh sáng, tưới tiêu"),
        bulletPoint("Truy xuất nguồn gốc: Ghi nhận toàn bộ vòng đời sản phẩm trên blockchain"),
        bulletPoint("Thương mại điện tử nông sản: Kết nối trực tiếp nông dân với người tiêu dùng"),

        heading("2.4.2 Thực trạng nông nghiệp Việt Nam và cơ hội", HeadingLevel.HEADING_3),
        p("Việt Nam là nước xuất khẩu nông sản hàng đầu thế giới (gạo, cà phê, hồ tiêu, cá tra...). Tuy nhiên, ngành nông nghiệp đối mặt với nhiều thách thức:"),
        bulletPoint("Chuỗi cung ứng phức tạp, nhiều khâu trung gian → nông dân nhận giá thấp, người tiêu dùng trả giá cao"),
        bulletPoint("Thiếu minh bạch về nguồn gốc → khó phân biệt nông sản sạch với nông sản thông thường"),
        bulletPoint("Hạn chế trong bảo quản và vận chuyển → tổn thất sau thu hoạch cao (20-30%)"),
        bulletPoint("Khó tiếp cận thị trường trực tiếp → phụ thuộc vào thương lái"),
        emptyLine(),
        p("Hệ thống máy bán hàng của nhóm đề xuất giải quyết các vấn đề trên bằng cách:"),
        bulletPoint("Tạo kênh phân phối trực tiếp Farm-to-Consumer qua máy bán hàng tự động"),
        bulletPoint("Sử dụng blockchain để truy xuất nguồn gốc minh bạch từ nông trại đến máy bán hàng"),
        bulletPoint("Giảm khâu trung gian → nông dân nhận 70-80% giá bán (thay vì 30-40% như hiện tại)"),
        bulletPoint("Người tiêu dùng quét mã QR xem toàn bộ hành trình sản phẩm"),

        heading("2.5 Tích hợp Blockchain-IoT trong Thành phố và Nông nghiệp thông minh", HeadingLevel.HEADING_2),
        heading("2.5.1 Mô hình BIoT (Blockchain + IoT)", HeadingLevel.HEADING_3),
        p("Sự kết hợp Blockchain-IoT (BIoT) tạo ra một hệ thống trong đó thiết bị IoT thu thập dữ liệu thế giới thực, còn blockchain đảm bảo dữ liệu đó không bị giả mạo. Trong thành phố thông minh, BIoT cho phép:"),
        bulletPoint("Cảm biến môi trường ghi dữ liệu chất lượng không khí lên blockchain → dữ liệu minh bạch cho người dân"),
        bulletPoint("Đèn đường thông minh báo cáo mức tiêu thụ năng lượng → tối ưu hóa và thanh toán ngang hàng"),
        bulletPoint("Máy bán hàng ghi nhận mọi giao dịch lên blockchain → chống gian lận doanh thu"),

        heading("2.5.2 Mô hình Farm-to-Consumer trên nền tảng Blockchain", HeadingLevel.HEADING_3),
        p("Mô hình Farm-to-Consumer (F2C) là xu hướng tiêu dùng hiện đại, nơi người tiêu dùng mua trực tiếp từ nông dân không qua trung gian. Blockchain đóng vai trò:"),
        numberedPoint(1, "Định danh số cho nông dân và nông trại (Digital Identity)"),
        numberedPoint(2, "Ghi nhận quá trình canh tác: ngày gieo trồng, loại phân bón, thuốc bảo vệ thực vật"),
        numberedPoint(3, "Ghi nhận quá trình thu hoạch, đóng gói, vận chuyển (kèm điều kiện bảo quản)"),
        numberedPoint(4, "Smart Contract tự động thanh toán cho nông dân khi sản phẩm được bán"),
        numberedPoint(5, "Người tiêu dùng quét QR trên máy bán hàng → xem toàn bộ lịch sử sản phẩm"),

        // ═══════ CHAPTER 3: SYSTEM ARCHITECTURE ═══════
        pageBreak(),
        heading("CHƯƠNG 3: KIẾN TRÚC HỆ THỐNG", HeadingLevel.HEADING_1),
        emptyLine(),
        heading("3.1 Tổng quan kiến trúc", HeadingLevel.HEADING_2),
        p("Hệ thống được thiết kế theo kiến trúc phân lớp 5 tầng, mỗi tầng đảm nhiệm một chức năng riêng biệt và giao tiếp với các tầng liền kề thông qua API và giao thức chuẩn:"),
        emptyLine(),
        createTable(
          ["Tầng", "Công nghệ", "Chức năng", "Đóng góp cho Smart City / Smart Agri"],
          [
            ["Tầng 5: Ứng dụng", "Flutter/Dart, Web3Auth, web3dart", "Giao diện người dùng, xác thực Web3, GPS, thanh toán ETH", "Trải nghiệm người dùng đô thị / Truy xuất nguồn gốc nông sản"],
            ["Tầng 4: Blockchain", "Ethereum Sepolia, Ethers.js v6", "Xử lý thanh toán, ghi nhận giao dịch, truy xuất nguồn gốc", "Minh bạch thanh toán / Hồ sơ số nông sản"],
            ["Tầng 3: Backend", "Node.js/Express, Firestore, Socket.io", "API, quản lý hàng đợi, xác minh giao dịch, WebSocket", "Điều phối đô thị / Quản lý chuỗi cung ứng"],
            ["Tầng 2: Firmware", "ESP32, PlatformIO, C++", "Poll lệnh, heartbeat, điều khiển motor, cảm biến, TFT", "Tự động hóa điểm bán / Giám sát chất lượng"],
            ["Tầng 1: Phần cứng", "ESP32 DevKit, ST7789, L9110S, TCRT5000, SG90", "Khung máy vật lý, 4 khe, cảm biến, servo, buzzer", "Thiết bị đầu cuối trong đô thị / Tủ phân phối nông sản"],
          ]
        ),
        emptyLine(),
        p("Luồng hoạt động tổng quan:"),
        numberedPoint(1, "Người dùng mở app → Đăng nhập Google qua Web3Auth → Nhận ví Ethereum"),
        numberedPoint(2, "App dùng GPS tìm máy bán hàng gần nhất trong bán kính 50m"),
        numberedPoint(3, "Người dùng tham gia hàng đợi ảo → Nhận vị trí và thời gian chờ"),
        numberedPoint(4, "Khi đến lượt (WebSocket turn_ready) → Xem danh sách sản phẩm + thông tin nguồn gốc"),
        numberedPoint(5, "Chọn sản phẩm → Gửi 0.001 ETH đến ví máy bán hàng"),
        numberedPoint(6, "Backend xác minh giao dịch 5 bước trên Sepolia → Tạo lệnh phân phối"),
        numberedPoint(7, "ESP32 poll lệnh → Kích hoạt động cơ → Cảm biến IR xác nhận sản phẩm"),
        numberedPoint(8, "ESP32 báo kết quả → Backend thông báo cho người dùng qua WebSocket"),
        numberedPoint(9, "Người dùng có thể quét QR để xem thông tin truy xuất nguồn gốc"),

        heading("3.1.1 Biểu đồ Use Case - Phân tích tác nhân và chức năng", HeadingLevel.HEADING_3),
        p("Hệ thống có 4 tác nhân chính (Actors) tương tác với 12 chức năng (Use Cases). Dưới đây là phân tích chi tiết:"),
        emptyLine(),
        p("TÁC NHÂN (ACTORS):", { bold: true }),
        createTable(
          ["Tác nhân", "Mô tả", "Vai trò trong hệ thống"],
          [
            ["Người dùng (User)", "Người dân đô thị, sinh viên, khách du lịch", "Tìm máy, xếp hàng, mua hàng, truy xuất nguồn gốc"],
            ["Nông dân / Hợp tác xã", "Nhà sản xuất nông sản", "Đăng ký sản phẩm, cập nhật thông tin canh tác, nhận thanh toán"],
            ["Quản trị viên (Admin)", "Người vận hành hệ thống", "Quản lý máy, sản phẩm, đơn hàng, xem báo cáo"],
            ["ESP32 (Thiết bị IoT)", "Máy bán hàng vật lý", "Nhận lệnh, phân phối sản phẩm, báo cáo trạng thái"],
          ]
        ),
        emptyLine(),
        p("BIỂU ĐỒ USE CASE:", { bold: true }),
        emptyLine(),
        p("NGƯỜI DÙNG (USER):", { bold: true }),
        p("├── UC1: Đăng nhập bằng Google (Web3Auth)"),
        p("│   └── <<include>> Tạo ví Ethereum (MPC)"),
        p("├── UC2: Xem danh sách máy bán hàng gần nhất"),
        p("│   └── <<include>> Định vị GPS + Tính khoảng cách Haversine"),
        p("├── UC3: Tham gia hàng đợi ảo"),
        p("│   └── <<extend>> Nhận thông báo WebSocket (turn_ready)"),
        p("├── UC4: Mua sản phẩm"),
        p("│   ├── <<include>> Gửi giao dịch ETH lên Sepolia"),
        p("│   ├── <<include>> Xác minh giao dịch (Backend)"),
        p("│   └── <<extend>> Retry nếu phân phối thất bại"),
        p("├── UC5: Xem lịch sử mua hàng"),
        p("├── UC6: Truy xuất nguồn gốc sản phẩm"),
        p("│   └── <<include>> Quét mã QR + Xem hồ sơ blockchain"),
        p("└── UC7: Kết thúc phiên mua sắm"),
        emptyLine(),
        p("NÔNG DÂN / HỢP TÁC XÃ:", { bold: true }),
        p("├── UC8: Đăng ký sản phẩm lên hệ thống"),
        p("│   └── <<include>> Tạo hồ sơ số (Digital Passport) trên blockchain"),
        p("├── UC9: Cập nhật thông tin canh tác, thu hoạch"),
        p("└── UC10: Theo dõi doanh thu và tồn kho"),
        emptyLine(),
        p("QUẢN TRỊ VIÊN (ADMIN):", { bold: true }),
        p("├── UC11: Quản lý máy bán hàng (thêm/sửa/xóa)"),
        p("├── UC12: Quản lý sản phẩm và khe chứa"),
        p("├── UC13: Xem báo cáo doanh thu (đối chiếu blockchain)"),
        p("└── UC14: Cấu hình hệ thống (giá, timeout, bán kính)"),
        emptyLine(),
        p("ESP32 (THIẾT BỊ IoT):", { bold: true }),
        p("├── UC15: Poll lệnh phân phối từ Backend (mỗi 2 giây)"),
        p("├── UC16: Điều khiển động cơ và cảm biến"),
        p("├── UC17: Gửi heartbeat cập nhật trạng thái (mỗi 10 giây)"),
        p("└── UC18: Hiển thị UI trên màn hình TFT"),
        emptyLine(),
        p("MỐI QUAN HỆ GIỮA CÁC TÁC NHÂN:", { bold: true }),
        p("Người dùng ──mua hàng──> ESP32 (qua Backend)"),
        p("Nông dân ──cung cấp──> Sản phẩm ──phân phối──> Người dùng"),
        p("Admin ──quản lý──> Toàn bộ hệ thống"),
        p("Blockchain ──xác minh──> Mọi giao dịch thanh toán"),
        p("WebSocket ──thông báo──> Người dùng + ESP32"),

        heading("3.2 Tầng Phần cứng (Hardware Layer)", HeadingLevel.HEADING_2),
        p("Hệ thống sử dụng ESP32 DOIT DevKit V1 làm bộ điều khiển trung tâm, kết nối với các ngoại vi:"),
        createTable(
          ["Thành phần", "Model", "Giao tiếp / GPIO", "Chức năng"],
          [
            ["Màn hình", "ST7789 240×320 TFT", "SPI (SCK:18, MOSI:23, RST:21, DC:22, CS:5)", "Giao diện người dùng tại máy"],
            ["Động cơ DC ×4", "H-Bridge L9110S", "16/17, 25/26, 27/14, 12/13", "Đẩy sản phẩm từng khe"],
            ["Cảm biến IR ×5", "TCRT5000", "ADC 32,33,34,35,39", "Phát hiện sản phẩm rơi + cửa"],
            ["Servo cửa", "SG90", "LEDC GPIO 15", "Đóng/mở cửa lấy hàng"],
            ["Còi Buzzer", "Piezo", "LEDC GPIO 4", "Âm thanh thông báo"],
            ["GPS (dự phòng)", "NEO-6M", "UART (RX:36, TX:37)", "Định vị máy"],
          ]
        ),

        heading("3.3 Tầng Firmware (Firmware Layer)", HeadingLevel.HEADING_2),
        p("Firmware ESP32 phát triển trên PlatformIO với Arduino Framework, tổ chức thành 8 module độc lập:"),
        bulletPoint("network/ — WiFi AP+STA đồng thời, Captive DNS, WebServer cấu hình"),
        bulletPoint("tft/ — 6 màn hình UI: WIFI_SETUP, IDLE, SELECT, PROCESSING, SUCCESS, ERROR"),
        bulletPoint("motor/ — Điều khiển 4 động cơ DC độc lập qua H-Bridge với PWM"),
        bulletPoint("buzzer/ — 3 giai điệu: startup, success, error"),
        bulletPoint("services/backend/ — Poll lệnh mỗi 2s, Heartbeat mỗi 10s"),
        bulletPoint("services/vending/ — Máy trạng thái: READY→PROCESSING→SUCCESS/ERROR"),
        bulletPoint("services/time/ — Đồng bộ NTP cho hiển thị thời gian thực"),
        bulletPoint("services/weather/ — Dữ liệu thời tiết phục vụ người dùng đô thị"),

        heading("3.4 Tầng Backend (Backend Layer)", HeadingLevel.HEADING_2),
        p("Backend Node.js/Express với Firestore NoSQL, cung cấp REST API đầy đủ:"),
        createTable(
          ["Nhóm API", "Endpoint chính", "Mô tả"],
          [
            ["Auth", "POST /api/auth/login", "Xác thực bằng chữ ký ví (EIP-191)"],
            ["Vending", "GET /api/vending?lat=&lng=", "Tìm máy theo GPS (Haversine, 50m)"],
            ["Queue", "POST /api/vending/:id/connect", "Tham gia hàng đợi, tự động serve nếu trống"],
            ["Queue", "GET /api/vending/:id/queue/status", "Kiểm tra vị trí hàng đợi"],
            ["Product", "POST /api/product/purchase", "Xác minh tx blockchain + tạo lệnh"],
            ["Product", "GET /api/product/machine/:id", "Danh sách sản phẩm + thông tin nguồn gốc"],
            ["Command", "GET /api/command/machine/:id/pending", "ESP32 poll lệnh chờ"],
            ["Command", "PUT /api/command/machine/:id/command/:cmdId/status", "ESP32 báo kết quả"],
            ["Trace", "GET /api/product/:id/trace", "Truy xuất nguồn gốc sản phẩm"],
          ]
        ),

        heading("3.5 Tầng Blockchain (Blockchain Layer)", HeadingLevel.HEADING_2),
        p("Đây là tầng cốt lõi đảm bảo tính minh bạch và chống gian lận cho toàn bộ hệ thống. Blockchain được tích hợp ở hai vai trò chính: (1) Xử lý thanh toán phi tập trung và (2) Lưu trữ hồ sơ truy xuất nguồn gốc sản phẩm."),
        emptyLine(),
        p("Thành phần kỹ thuật:", { bold: true }),
        bulletPoint("Mạng lưới: Ethereum Sepolia Testnet (PoS), Chain ID: 11155111"),
        bulletPoint("RPC Provider: ethereum-sepolia-rpc.publicnode.com"),
        bulletPoint("Thư viện Backend: Ethers.js v6 (provider.getTransaction, provider.getTransactionReceipt)"),
        bulletPoint("Thư viện Mobile: web3dart (Web3Client, sendTransaction, getTransactionReceipt)"),
        bulletPoint("Ví thanh toán: 0x94988621cDd1aCEAa0284f65cb2EBE0B40AD7c85"),
        bulletPoint("Đơn vị thanh toán: ETH (0.001 ETH / sản phẩm)"),
        bulletPoint("Xác thực người dùng: Web3Auth MPC + EIP-191 Signature"),

        emptyLine(),
        p("Sơ đồ luồng xử lý giao dịch Blockchain:", { bold: true }),
        emptyLine(),
        p("NGƯỜI DÙNG (MOBILE APP) → [1] Chọn sản phẩm → [2] WalletService.sendTransaction() → [3] Giao dịch gửi lên Sepolia Mempool → [4] Validator chọn giao dịch → [5] Giao dịch được khai thác vào khối → [6] App nhận txHash → [7] App gửi POST /api/product/purchase {txHash} → [8] BACKEND: Bước 1 - provider.getTransaction(txHash) → [9] Bước 2 - Kiểm tra chainId (11155111) → [10] Bước 3 - Kiểm tra địa chỉ nhận (VENDING_WALLET) → [11] Bước 4 - Kiểm tra số tiền (>= 0.001 ETH) → [12] Bước 5 - Poll receipt (tối đa 60s) → [13] Xác minh thành công → [14] Tạo Order + Dispense Command → [15] ESP32 nhận lệnh → [16] Phân phối sản phẩm → [17] Báo kết quả → [18] WebSocket thông báo cho người dùng", { italics: true }),
        emptyLine(),
        p("Thời gian mỗi bước:", { bold: true }),
        createTable(
          ["Bước", "Mô tả", "Thời gian (giây)", "Ghi chú"],
          [
            ["1-3", "App tạo và gửi giao dịch", "1-2s", "Ký bằng private key MPC"],
            ["4-5", "Validator khai thác vào khối", "12-15s", "Sepolia PoS block time"],
            ["6-7", "App gửi txHash lên backend", "0.2-0.5s", "HTTP request"],
            ["8-11", "Backend kiểm tra txHash, chain, to, value", "0.1-0.3s", "Đọc dữ liệu on-chain"],
            ["12", "Chờ transaction receipt", "0-45s", "Poll mỗi 3s × tối đa 20 lần"],
            ["13-14", "Tạo order + command", "0.2-0.5s", "Ghi Firestore"],
            ["15-17", "ESP32 poll + phân phối", "2-5s", "Motor + IR sensor"],
            ["18", "Thông báo WebSocket", "0.1s", "Socket.io emit"],
          ]
        ),

        heading("3.6 Tầng Ứng dụng Di động (Mobile Layer)", HeadingLevel.HEADING_2),
        p("Ứng dụng Flutter 3.x với kiến trúc BLoC (Business Logic Component), sử dụng ngôn ngữ Dart. Ứng dụng được thiết kế với 6 màn hình chính, mỗi màn hình đảm nhiệm một bước trong hành trình người dùng."),
        emptyLine(),
        p("Phân tích giao diện người dùng:", { bold: true }),
        createTable(
          ["Màn hình", "Chức năng chính", "Thành phần UI", "Công nghệ"],
          [
            ["Login Screen", "Đăng nhập Google → tạo ví Web3", "Logo VENDX, nút Google Sign-in, animation", "Web3Auth Flutter SDK, web3dart"],
            ["Home Screen", "Dashboard: balance, history, máy gần nhất", "Số dư ETH, danh sách giao dịch, horizontal scroll máy", "BLoC (HomeCubit), Geolocator, ApiService"],
            ["Vending Machine List", "Danh sách máy theo GPS, khoảng cách", "Card máy (tên, trạng thái, khoảng cách), pull-to-refresh", "BLoC (VendingCubit), GPS, Haversine"],
            ["Waiting Lobby", "Hàng đợi ảo + WebSocket", "Vị trí hàng đợi, đồng hồ đếm ngược, số người phía trước", "BLoC (QueueCubit), SocketService"],
            ["Purchase Screen", "Chọn sản phẩm + gửi ETH", "Grid sản phẩm, giá ETH, nút mua, dialog xác nhận tx", "BLoC (PurchaseCubit), WalletService"],
            ["Traceability Screen", "Truy xuất nguồn gốc nông sản", "Timeline từ nông trại → máy, QR code, txHash link", "ApiService, Etherscan URL"],
          ]
        ),

        heading("3.7 Sơ đồ mạch IoT - Phần cứng ESP32", HeadingLevel.HEADING_2),
        p("Sơ đồ kết nối phần cứng của hệ thống máy bán hàng được thiết kế với ESP32 là bộ điều khiển trung tâm, kết nối với 6 nhóm ngoại vi chính qua các giao thức khác nhau:"),
        emptyLine(),
        p("SƠ ĐỒ MẠCH TỔNG QUAN:", { bold: true }),
        emptyLine(),
        p("ESP32 DOIT DevKit V1 (Trung tâm)", { bold: true }),
        p("│"),
        p("├── [SPI Bus] ── MÀN HÌNH ST7789 TFT 240×320", { bold: true }),
        p("│   ├── SCK  → GPIO 18  (Clock)"),
        p("│   ├── MOSI → GPIO 23  (Data)"),
        p("│   ├── RST  → GPIO 21  (Reset)"),
        p("│   ├── DC   → GPIO 22  (Data/Command)"),
        p("│   └── CS   → GPIO 5   (Chip Select)"),
        p("│"),
        p("├── [GPIO] ── 4 ĐỘNG CƠ DC (H-Bridge L9110S) ── ĐẨY SẢN PHẨM", { bold: true }),
        p("│   ├── Khe A1: INA=GPIO 16, INB=GPIO 17  (PWM)"),
        p("│   ├── Khe A2: INA=GPIO 25, INB=GPIO 26  (PWM)"),
        p("│   ├── Khe A3: INA=GPIO 27, INB=GPIO 14  (PWM)"),
        p("│   └── Khe B1: INA=GPIO 12, INB=GPIO 13  (PWM)"),
        p("│"),
        p("├── [ADC] ── 5 CẢM BIẾN HỒNG NGOẠI TCRT5000 ── PHÁT HIỆN SẢN PHẨM", { bold: true }),
        p("│   ├── IR Khe 1: GPIO 32 (Analog)"),
        p("│   ├── IR Khe 2: GPIO 33 (Analog)"),
        p("│   ├── IR Khe 3: GPIO 34 (Analog)"),
        p("│   ├── IR Khe 4: GPIO 35 (Analog)"),
        p("│   └── IR Cửa:  GPIO 39 (Analog)"),
        p("│"),
        p("├── [LEDC PWM] ── SERVO CỬA SG90 ── ĐÓNG/MỞ CỬA LẤY HÀNG", { bold: true }),
        p("│   └── GPIO 15, Channel 1, Freq 50Hz, Res 16-bit"),
        p("│       ├── Góc đóng: 0° (1638 μs)"),
        p("│       └── Góc mở:  90° (4915 μs)"),
        p("│"),
        p("├── [LEDC PWM] ── CÒI BUZZER PIEZO ── ÂM THANH THÔNG BÁO", { bold: true }),
        p("│   └── GPIO 4"),
        p("│       ├── Giai điệu Startup: Tần số tăng dần"),
        p("│       ├── Giai điệu Success: 3 nốt cao"),
        p("│       └── Giai điệu Error:  2 nốt thấp"),
        p("│"),
        p("└── [UART] ── GPS NEO-6M (DỰ PHÒNG) ── ĐỊNH VỊ MÁY", { bold: true }),
        p("    ├── RX → GPIO 36"),
        p("    └── TX → GPIO 37"),
        emptyLine(),

        heading("3.8 Sơ đồ luồng hoạt động toàn hệ thống", HeadingLevel.HEADING_2),
        p("Luồng hoạt động end-to-end từ khi người dùng mở app đến khi nhận sản phẩm:"),
        emptyLine(),
        p("GIAI ĐOẠN 1: KHỞI TẠO (2-5 giây)", { bold: true }),
        p("NGƯỜI DÙNG → Mở App Flutter → Web3Auth Google Login → Nhận Private Key (MPC) → Khởi tạo WalletService → Kết nối Sepolia RPC → GET /api/auth/nonce → Ký nonce (EIP-191) → POST /api/auth/login → Nhận JWT Token"),
        emptyLine(),
        p("GIAI ĐOẠN 2: TÌM MÁY (1-3 giây)", { bold: true }),
        p("NGƯỜI DÙNG → Geolocator.getCurrentPosition() → Gửi (lat, lng) → GET /api/vending → Backend tính Haversine → Lọc máy bán kính 50m → Sắp xếp khoảng cách → Trả danh sách → Hiển thị VendingMachineList"),
        emptyLine(),
        p("GIAI ĐOẠN 3: HÀNG ĐỢI (0-180 giây)", { bold: true }),
        p("NGƯỜI DÙNG → Chọn máy → POST /api/vending/:id/connect → Backend tạo QueueEntry → Kiểm tra có ai đang serving? → NẾU KHÔNG: Auto-serve người này → NẾU CÓ: Xếp sau → Trả vị trí + thời gian chờ → Socket.io subscribe machine → App hiển thị WaitingLobby → KHI ĐẾN LƯỢT: Socket emit 'turn_ready' → App hiển thị 'Đến lượt bạn!' → Đồng hồ 120s bắt đầu đếm ngược"),
        emptyLine(),
        p("GIAI ĐOẠN 4: THANH TOÁN BLOCKCHAIN (15-30 giây)", { bold: true }),
        p("NGƯỜI DÙNG → Vào Purchase Screen → Chọn sản phẩm → Nhấn 'Mua' → WalletService.sendTransaction({to: VENDING_WALLET, value: 0.001}) → web3dart ký giao dịch → Gửi lên Sepolia Mempool → Đợi validator khai thác (12-15s) → Nhận txHash → App gửi POST /api/product/purchase {txHash} → BACKEND: verifyPayment(txHash) 5 bước → Tạo Order → Tạo DispenseCommand → ESP32 poll nhận lệnh"),
        emptyLine(),
        p("GIAI ĐOẠN 5: PHÂN PHỐI SẢN PHẨM (2-5 giây)", { bold: true }),
        p("ESP32 → Nhận lệnh từ GET /pending → dispatchCommand() → changeState(PROCESSING) → turnMotor(slot, 255) → openDoor() → ĐỌC CẢM BIẾN IR → NẾU IR PHÁT HIỆN: stopMotor() → closeDoor() → changeState(SUCCESS) → playSuccessBuzzer() → PUT /cmd/status {success} → Backend cập nhật Order → Socket emit 'purchase_complete' → App hiển thị SUCCESS → NẾU TIMEOUT 3s: stopMotor() → closeDoor() → changeState(ERROR) → playErrorBuzzer() → PUT /cmd/status {error} → Socket emit → App hiển thị ERROR + nút Retry"),
        emptyLine(),
        p("SƠ ĐỒ MÁY TRẠNG THÁI ESP32:", { bold: true }),
        createTable(
          ["Trạng thái", "Mô tả", "Điều kiện chuyển tiếp", "Hành động"],
          [
            ["READY", "Sẵn sàng nhận lệnh", "Nhận được command từ API", "Chuyển sang PROCESSING"],
            ["PROCESSING", "Đang phân phối sản phẩm", "IR phát hiện sản phẩm", "→ SUCCESS"],
            ["PROCESSING", "Đang phân phối sản phẩm", "Quá 3 giây không có IR", "→ ERROR"],
            ["SUCCESS", "Phân phối thành công", "Báo cáo backend xong", "→ READY"],
            ["ERROR", "Phân phối thất bại", "Báo cáo backend xong / Retry", "→ READY"],
          ]
        ),
        emptyLine(),
        p("GIAI ĐOẠN 6: HOÀN TẤT (tùy chọn)", { bold: true }),
        p("NGƯỜI DÙNG → Có thể MUA TIẾP (quay lại Giai đoạn 4) hoặc KẾT THÚC → POST /api/vending/:id/finish-shopping → Backend completeServing → serveNext() → Socket emit 'turn_ready' cho người kế tiếp"),
        emptyLine(),
        p("SƠ ĐỒ TUẦN TỰ END-TO-END:", { bold: true }),
        p("USER APP ──[Login]──> BACKEND ──[Verify]──> BLOCKCHAIN"),
        p("USER APP ──[GPS]──> BACKEND ──[Haversine]──> FIRESTORE"),
        p("USER APP ──[Join Queue]──> BACKEND ──[Socket]──> USER APP"),
        p("USER APP ──[Send ETH]──> BLOCKCHAIN ──[Confirm]──> BACKEND"),
        p("BACKEND ──[Command]──> ESP32 ──[Motor+IR]──> SẢN PHẨM"),
        p("ESP32 ──[Result]──> BACKEND ──[Socket]──> USER APP"),

        // ═══════ CHAPTER 4: SMART CITY ═══════
        pageBreak(),
        heading("CHƯƠNG 4: ỨNG DỤNG TRONG THÀNH PHỐ THÔNG MINH", HeadingLevel.HEADING_1),
        emptyLine(),
        heading("4.1 Hệ thống máy bán hàng như một dịch vụ đô thị thông minh", HeadingLevel.HEADING_2),
        p("Trong bối cảnh thành phố thông minh, máy bán hàng tự động không chỉ là một thiết bị bán lẻ đơn thuần mà là một thành phần trong hệ sinh thái dịch vụ đô thị tích hợp. Hệ thống của nhóm được thiết kế để đáp ứng các tiêu chí của một dịch vụ đô thị thông minh:"),

        heading("4.1.1 Tìm kiếm và định vị thông minh", HeadingLevel.HEADING_3),
        p("Người dân trong thành phố có thể sử dụng ứng dụng di động để tìm máy bán hàng gần nhất. Hệ thống sử dụng công thức Haversine để tính khoảng cách chính xác dựa trên tọa độ GPS:"),
        p("Công thức Haversine: d = 2R × arcsin(√(sin²(Δlat/2) + cos(lat1)cos(lat2)sin²(Δlng/2))), với R = 6371km (bán kính Trái Đất). Backend lọc các máy trong bán kính 50m (có thể cấu hình), sắp xếp theo khoảng cách tăng dần, trả về danh sách cho người dùng."),
        p("Tính năng này đặc biệt hữu ích trong môi trường đô thị đông đúc, nơi có nhiều máy bán hàng được phân bố. Người dân không cần phải đi bộ xa để tìm máy, giảm thời gian di chuyển và ùn tắc tại các điểm tập trung."),

        heading("4.1.2 Hàng đợi ảo - Giải pháp cho không gian công cộng", HeadingLevel.HEADING_3),
        p("Tại các địa điểm công cộng đông người (bến xe, ga tàu, trường học, bệnh viện), hàng đợi vật lý trước máy bán hàng gây ùn tắc và lãng phí thời gian. Hệ thống giải quyết vấn đề này bằng hàng đợi ảo:"),
        numberedPoint(1, "Người dùng tham gia hàng đợi từ xa qua app (không cần đứng xếp hàng vật lý)"),
        numberedPoint(2, "Hệ thống FIFO đảm bảo công bằng: người đến trước được phục vụ trước"),
        numberedPoint(3, "WebSocket thông báo theo thời gian thực: vị trí hiện tại, thời gian chờ ước tính"),
        numberedPoint(4, "Khi đến lượt: nhận thông báo \"turn_ready\", có 120 giây để thực hiện giao dịch"),
        numberedPoint(5, "Nếu quá hạn: tự động chuyển lượt cho người kế tiếp, tránh nghẽn hệ thống"),
        emptyLine(),
        p("Cơ chế này đặc biệt phù hợp với mô hình thành phố thông minh, nơi mọi dịch vụ công cộng đều hướng đến sự thuận tiện và hiệu quả cho người dân."),

        heading("4.1.3 Thanh toán không tiền mặt - Hướng tới xã hội Cashless", HeadingLevel.HEADING_3),
        p("Chính phủ Việt Nam đã phê duyệt Đề án phát triển thanh toán không dùng tiền mặt giai đoạn 2021-2025. Hệ thống máy bán hàng của nhóm đóng góp vào mục tiêu này bằng cách:"),
        bulletPoint("100% giao dịch được thực hiện qua blockchain, không sử dụng tiền mặt"),
        bulletPoint("Người dùng không cần mang theo ví vật lý hay thẻ ngân hàng"),
        bulletPoint("Mọi giao dịch được ghi nhận công khai → dễ dàng kiểm toán và báo cáo thuế"),
        bulletPoint("Tích hợp với ví điện tử Web3 → tiền đề cho CBDC (tiền số quốc gia) trong tương lai"),

        heading("4.1.4 Blockchain - Nền tảng minh bạch cho giao dịch đô thị", HeadingLevel.HEADING_3),
        p("Trong bối cảnh thành phố thông minh, blockchain không chỉ là công cụ thanh toán mà còn là nền tảng đảm bảo tính minh bạch và trách nhiệm giải trình cho mọi giao dịch công cộng:"),
        emptyLine(),
        p("Phân tích lợi ích của Blockchain trong thanh toán đô thị:", { bold: true }),
        createTable(
          ["Tiêu chí", "Thanh toán truyền thống", "Thanh toán Blockchain (hệ thống này)", "Lợi ích"],
          [
            ["Minh bạch", "Do ngân hàng/nhà vận hành kiểm soát", "Mọi giao dịch công khai trên Sepolia Etherscan", "Người dân có thể kiểm tra độc lập"],
            ["Chống gian lận", "Có thể sửa đổi log giao dịch", "Dữ liệu bất biến, không thể sửa/xóa", "Nhà vận hành không thể gian lận doanh thu"],
            ["Kiểm toán", "Cần truy cập hệ thống nội bộ", "Kiểm toán trực tiếp từ blockchain explorer", "Cơ quan thuế kiểm tra dễ dàng"],
            ["Tranh chấp", "Cần bên thứ 3 phân xử", "txHash là bằng chứng không thể chối cãi", "Giải quyết tranh chấp nhanh chóng"],
            ["Chi phí", "Phí ngân hàng 2-3%", "Phí gas ~0.000021 ETH (~$0.05)", "Chi phí thấp hơn nhiều"],
            ["Tốc độ", "1-3 ngày (thanh toán thẻ)", "12-20 giây (1 block confirmation)", "Nhanh hơn hàng nghìn lần"],
            ["Toàn cầu", "Giới hạn theo quốc gia", "Không biên giới, ai cũng dùng được", "Phù hợp thành phố du lịch quốc tế"],
          ]
        ),

        heading("4.2 Tích hợp với hạ tầng thành phố thông minh", HeadingLevel.HEADING_2),
        heading("4.2.1 Kết nối với hệ thống quản lý đô thị", HeadingLevel.HEADING_3),
        p("Hệ thống được thiết kế với khả năng mở rộng để kết nối với các hệ thống quản lý đô thị thông minh khác:"),
        bulletPoint("Hệ thống giao thông thông minh: Đề xuất vị trí đặt máy dựa trên lưu lượng người đi bộ"),
        bulletPoint("Hệ thống năng lượng: Máy sử dụng năng lượng mặt trời, báo cáo mức tiêu thụ về trung tâm"),
        bulletPoint("Hệ thống quản lý chất thải: Cảm biến báo cáo lượng rác tại khu vực máy"),
        bulletPoint("Hệ thống an ninh: Camera tích hợp (tương lai), cảnh báo phá hoại qua mạng đô thị"),

        heading("4.2.2 Dữ liệu cho quy hoạch đô thị", HeadingLevel.HEADING_3),
        p("Dữ liệu giao dịch từ hệ thống máy bán hàng (được lưu trữ minh bạch trên blockchain) cung cấp thông tin quý giá cho công tác quy hoạch đô thị:"),
        bulletPoint("Phân tích nhu cầu tiêu dùng theo khu vực, thời gian trong ngày"),
        bulletPoint("Xác định điểm nóng (hotspot) cần thêm máy hoặc điều chỉnh sản phẩm"),
        bulletPoint("Đo lường hiệu quả của các chính sách đô thị (ví dụ: sau khi mở công viên mới, nhu cầu nước uống tăng bao nhiêu %)"),
        bulletPoint("Dự báo xu hướng tiêu dùng bằng AI/ML dựa trên dữ liệu lịch sử"),

        heading("4.3 Mô hình triển khai trong thành phố", HeadingLevel.HEADING_2),
        p("Đề xuất mô hình triển khai hệ thống máy bán hàng thông minh trong thành phố:"),
        createTable(
          ["Vị trí", "Loại sản phẩm", "Đối tượng", "Lợi ích"],
          [
            ["Bến xe, ga tàu", "Nước uống, đồ ăn nhanh, khẩu trang", "Hành khách", "Tiện lợi, nhanh chóng, giảm ùn tắc"],
            ["Trường đại học", "Đồ uống, snack, văn phòng phẩm", "Sinh viên", "Tiết kiệm thời gian giữa giờ"],
            ["Bệnh viện", "Nước, đồ ăn nhẹ, vật tư y tế", "Bệnh nhân, người nhà", "Phục vụ 24/7, giảm tải căng-tin"],
            ["Công viên", "Nước, kem, đồ chơi trẻ em", "Người dân", "Nâng cao trải nghiệm công viên"],
            ["Chung cư", "Nông sản sạch, đồ khô, sữa", "Cư dân", "Farm-to-Consumer tiện lợi"],
            ["Khu công nghiệp", "Đồ ăn trưa, nước uống", "Công nhân", "Tiết kiệm thời gian nghỉ trưa"],
          ]
        ),

        // ═══════ CHAPTER 5: SMART AGRICULTURE ═══════
        pageBreak(),
        heading("CHƯƠNG 5: ỨNG DỤNG TRONG NÔNG NGHIỆP THÔNG MINH", HeadingLevel.HEADING_1),
        emptyLine(),
        heading("5.1 Mô hình Farm-to-Consumer qua máy bán hàng thông minh", HeadingLevel.HEADING_2),
        p("Mô hình Farm-to-Consumer (F2C) là giải pháp kết nối trực tiếp nông dân với người tiêu dùng thông qua nền tảng máy bán hàng thông minh. Đây là một ứng dụng đột phá của công nghệ blockchain và IoT trong lĩnh vực nông nghiệp."),

        heading("5.1.1 Bài toán chuỗi cung ứng nông sản truyền thống", HeadingLevel.HEADING_3),
        p("Chuỗi cung ứng nông sản truyền thống tại Việt Nam thường qua 5-7 khâu trung gian:"),
        p("Nông dân → Thương lái → Chợ đầu mối → Nhà phân phối → Siêu thị/Cửa hàng → Người tiêu dùng. Mỗi khâu trung gian làm tăng giá 15-20%, dẫn đến:"),
        bulletPoint("Nông dân chỉ nhận được 30-40% giá bán cuối cùng"),
        bulletPoint("Người tiêu dùng trả giá cao gấp 3-4 lần giá tại nông trại"),
        bulletPoint("Khó truy xuất nguồn gốc khi có sự cố an toàn thực phẩm"),
        bulletPoint("Nông sản dễ bị trà trộn, giả mạo xuất xứ (ví dụ: rau Trung Quốc gắn mác Đà Lạt)"),

        heading("5.1.2 Giải pháp F2C của hệ thống", HeadingLevel.HEADING_3),
        p("Hệ thống máy bán hàng thông minh rút ngắn chuỗi cung ứng xuống còn 2-3 bước:"),
        p("Nông dân/Hợp tác xã → (Sơ chế, đóng gói) → Máy bán hàng thông minh → Người tiêu dùng."),
        emptyLine(),
        p("Lợi ích cụ thể:", { bold: true }),
        bulletPoint("Nông dân nhận 70-80% giá bán (thay vì 30-40%), tăng thu nhập đáng kể"),
        bulletPoint("Người tiêu dùng mua nông sản tươi, giá hợp lý hơn 20-30%"),
        bulletPoint("Blockchain ghi nhận toàn bộ hành trình → minh bạch tuyệt đối"),
        bulletPoint("Hợp tác xã có thể quản lý nhiều máy bán hàng như một chuỗi cửa hàng tự động"),

        heading("5.2 Truy xuất nguồn gốc nông sản qua Blockchain", HeadingLevel.HEADING_2),
        heading("5.2.1 Cơ chế truy xuất nguồn gốc", HeadingLevel.HEADING_3),
        p("Mỗi sản phẩm nông nghiệp trong hệ thống được gắn một mã định danh duy nhất (Product ID), liên kết với một hồ sơ số (Digital Passport) trên blockchain. Hồ sơ này bao gồm:"),
        createTable(
          ["Giai đoạn", "Thông tin ghi nhận", "Phương thức xác thực"],
          [
            ["Gieo trồng", "Ngày gieo, giống cây, vị trí GPS nông trại", "Nông dân ký giao dịch bằng ví Web3"],
            ["Chăm sóc", "Phân bón, thuốc BVTV, lượng nước tưới", "Cảm biến IoT ghi dữ liệu tự động"],
            ["Thu hoạch", "Ngày thu hoạch, sản lượng, điều kiện thời tiết", "QR code quét tại thời điểm thu hoạch"],
            ["Sơ chế", "Phương pháp, cơ sở chế biến, chứng nhận ATTP", "Đơn vị sơ chế xác nhận qua blockchain"],
            ["Vận chuyển", "Thời gian, nhiệt độ, độ ẩm trong quá trình vận chuyển", "Cảm biến IoT trên xe lạnh"],
            ["Phân phối", "Máy bán hàng số mấy, thời gian nhập hàng", "Smart Contract tự động ghi nhận"],
            ["Bán cho người dùng", "Thời gian mua, địa chỉ ví người mua", "Giao dịch ETH trên Sepolia"],
          ]
        ),

        heading("5.2.2 Quy trình người dùng truy xuất nguồn gốc", HeadingLevel.HEADING_3),
        numberedPoint(1, "Người dùng mua sản phẩm từ máy bán hàng"),
        numberedPoint(2, "App hiển thị mã QR của sản phẩm (dựa trên txHash của giao dịch)"),
        numberedPoint(3, "Người dùng quét mã QR → App gọi API /api/product/:id/trace"),
        numberedPoint(4, "Backend truy vấn blockchain và Firestore → trả về toàn bộ hồ sơ sản phẩm"),
        numberedPoint(5, "App hiển thị timeline trực quan: từ nông trại → máy bán hàng → tay người dùng"),
        numberedPoint(6, "Người dùng có thể xác minh độc lập trên Etherscan (với txHash)"),

        heading("5.3 Lợi ích cho các bên liên quan", HeadingLevel.HEADING_2),
        p("Mô hình F2C + Blockchain mang lại lợi ích cho tất cả các bên:"),
        emptyLine(),
        p("Đối với nông dân và hợp tác xã:", { bold: true }),
        bulletPoint("Tiếp cận trực tiếp thị trường đô thị không qua trung gian"),
        bulletPoint("Tăng thu nhập (70-80% giá bán so với 30-40% hiện tại)"),
        bulletPoint("Xây dựng thương hiệu nông sản riêng, được người tiêu dùng nhận diện"),
        bulletPoint("Dữ liệu tiêu thụ giúp lập kế hoạch sản xuất chính xác hơn"),
        bulletPoint("Thanh toán tự động qua smart contract khi sản phẩm được bán"),
        emptyLine(),
        p("Đối với người tiêu dùng đô thị:", { bold: true }),
        bulletPoint("Tiếp cận nông sản tươi, sạch, giá hợp lý 24/7"),
        bulletPoint("Minh bạch nguồn gốc: biết chính xác ai trồng, trồng ở đâu, dùng phân bón gì"),
        bulletPoint("An tâm về an toàn thực phẩm nhờ chứng nhận trên blockchain"),
        bulletPoint("Góp phần hỗ trợ nông dân địa phương, phát triển kinh tế nông thôn"),
        emptyLine(),
        p("Đối với chính quyền và xã hội:", { bold: true }),
        bulletPoint("Thúc đẩy chuyển đổi số trong nông nghiệp"),
        bulletPoint("Giảm thất thoát sau thu hoạch nhờ chuỗi cung ứng ngắn"),
        bulletPoint("Tạo việc làm cho lao động vận hành máy, hậu cần"),
        bulletPoint("Dữ liệu minh bạch hỗ trợ quản lý an toàn thực phẩm"),

        heading("5.4 Tích hợp IoT trong giám sát chất lượng nông sản", HeadingLevel.HEADING_2),
        p("Ngoài chức năng bán hàng, hệ thống còn tích hợp các cảm biến IoT trong quá trình bảo quản và vận chuyển nông sản:"),
        bulletPoint("Cảm biến nhiệt độ, độ ẩm trong tủ lạnh của máy bán hàng → đảm bảo điều kiện bảo quản tối ưu"),
        bulletPoint("Cảm biến khí ethylene → phát hiện nông sản chín quá mức, cảnh báo thay thế"),
        bulletPoint("Dữ liệu cảm biến được ghi lên blockchain → bằng chứng không thể thay đổi về điều kiện bảo quản"),
        bulletPoint("Kết hợp AI để dự đoán thời gian tươi ngon còn lại của sản phẩm → giảm giá tự động khi gần hết hạn"),

        // ═══════ CHAPTER 6: CONCLUSION ═══════
        pageBreak(),
        heading("CHƯƠNG 6: KẾT LUẬN VÀ HƯỚNG PHÁT TRIỂN", HeadingLevel.HEADING_1),
        emptyLine(),
        heading("6.1 Kết quả đạt được", HeadingLevel.HEADING_2),
        p("Sau quá trình nghiên cứu và phát triển, nhóm đã xây dựng thành công Hệ thống máy bán hàng tự động thông minh tích hợp Blockchain và IoT, với các kết quả nổi bật:"),

        p("Về Công nghệ Blockchain:", { bold: true }),
        bulletPoint("Tích hợp thành công Ethereum Sepolia Testnet cho thanh toán phi tập trung"),
        bulletPoint("Cơ chế xác minh giao dịch 5 bước, đảm bảo chính xác và chống gian lận"),
        bulletPoint("Mỗi giao dịch ghi nhận vĩnh viễn trên chuỗi khối → minh bạch, có thể kiểm toán"),
        bulletPoint("Xác thực người dùng qua ví Web3 (EIP-191), loại bỏ username/password"),
        bulletPoint("Nền tảng cho truy xuất nguồn gốc nông sản qua blockchain"),

        p("Về Công nghệ IoT:", { bold: true }),
        bulletPoint("Firmware ESP32 hoàn chỉnh với 8 module độc lập"),
        bulletPoint("Điều khiển 4 khe sản phẩm với động cơ DC và cảm biến hồng ngoại (độ chính xác >95%)"),
        bulletPoint("Màn hình TFT 6 trạng thái giao diện, giao tiếp WiFi AP+STA"),
        bulletPoint("Poll API + Heartbeat, đồng bộ thời gian thực với backend"),

        p("Về Ứng dụng trong Thành phố thông minh:", { bold: true }),
        bulletPoint("Điểm bán lẻ tự động 24/7, tìm kiếm theo GPS (bán kính 50m)"),
        bulletPoint("Hàng đợi ảo FIFO với WebSocket real-time → giảm ùn tắc nơi công cộng"),
        bulletPoint("Thanh toán không tiền mặt qua blockchain → đóng góp vào xã hội cashless"),
        bulletPoint("Dữ liệu giao dịch công khai phục vụ quy hoạch đô thị"),

        p("Về Ứng dụng trong Nông nghiệp thông minh:", { bold: true }),
        bulletPoint("Mô hình Farm-to-Consumer rút ngắn chuỗi cung ứng từ 5-7 khâu xuống 2-3 khâu"),
        bulletPoint("Truy xuất nguồn gốc 7 giai đoạn trên blockchain → minh bạch từ nông trại đến bàn ăn"),
        bulletPoint("Tăng thu nhập cho nông dân (70-80% giá bán) và giảm giá cho người tiêu dùng"),
        bulletPoint("Tích hợp cảm biến IoT giám sát chất lượng nông sản trong bảo quản"),

        heading("6.2 Hạn chế", HeadingLevel.HEADING_2),
        numberedPoint(1, "Smart Contract chưa hoàn thiện: Hiện dùng raw ETH transfer. Cần phát triển smart contract tùy chỉnh cho truy xuất nguồn gốc và thanh toán tự động cho nông dân."),
        numberedPoint(2, "Quy mô thử nghiệm nhỏ: Mới có 1 máy với 4 khe, cần mở rộng để đánh giá hiệu quả thực tế trong môi trường đô thị."),
        numberedPoint(3, "Chưa tích hợp đầy đủ với hạ tầng thành phố: Cần API kết nối với hệ thống giao thông, năng lượng, chất thải của thành phố."),
        numberedPoint(4, "Phụ thuộc tốc độ blockchain: Thời gian xác nhận giao dịch 12-20 giây có thể ảnh hưởng trải nghiệm."),
        numberedPoint(5, "Chưa có cơ chế bảo quản lạnh sâu: Phù hợp cho nông sản khô, chưa tối ưu cho rau củ quả tươi cần bảo quản 2-8°C."),

        heading("6.3 Hướng phát triển", HeadingLevel.HEADING_2),
        p("Ngắn hạn (1-3 tháng):", { bold: true }),
        numberedPoint(1, "Phát triển Smart Contract Solidity cho: thanh toán đa sản phẩm, tự động chia hoa hồng cho nông dân, cơ chế refund nếu sản phẩm lỗi"),
        numberedPoint(2, "Tích hợp stablecoin (USDC/USDT) để giảm biến động giá, phù hợp với người dùng phổ thông"),
        numberedPoint(3, "Xây dựng Dashboard cho nông dân/hợp tác xã theo dõi doanh thu, tồn kho theo thời gian thực"),
        emptyLine(),
        p("Trung hạn (3-6 tháng):", { bold: true }),
        numberedPoint(4, "Tích hợp Layer 2 (Arbitrum/Optimism) → giảm phí gas, tăng tốc giao dịch"),
        numberedPoint(5, "Triển khai mô hình thí điểm: đặt 5-10 máy tại chung cư, trường học ở Hà Nội, kết nối với 2-3 hợp tác xã nông nghiệp"),
        numberedPoint(6, "Phát triển module AI: dự đoán nhu cầu sản phẩm, tối ưu lịch nhập hàng, phát hiện bất thường"),
        numberedPoint(7, "Tích hợp cảm biến chất lượng không khí, tiếng ồn vào máy → đóng góp dữ liệu môi trường cho thành phố"),
        emptyLine(),
        p("Dài hạn (6-12 tháng):", { bold: true }),
        numberedPoint(8, "Tokenomics: Phát hành utility token cho hệ sinh thái (giảm giá khi dùng token, staking nhận ưu đãi)"),
        numberedPoint(9, "Mở rộng ra các thành phố lớn: Hà Nội, TP.HCM, Đà Nẵng, Hải Phòng"),
        numberedPoint(10, "Tích hợp với đề án thành phố thông minh của chính phủ: kết nối với trung tâm điều hành đô thị (IOC)"),
        numberedPoint(11, "Phát triển tiêu chuẩn mở cho máy bán hàng nông sản: cho phép nhiều nhà sản xuất cùng tham gia hệ sinh thái"),
        numberedPoint(12, "Nghiên cứu chuyển đổi từ Testnet sang Mainnet khi quy mô đủ lớn và hành lang pháp lý rõ ràng"),

        heading("6.4 Bài học kinh nghiệm", HeadingLevel.HEADING_2),
        numberedPoint(1, "Công nghệ phải phục vụ con người: Blockchain và IoT là công cụ; giá trị thực sự nằm ở việc giải quyết vấn đề của người dân đô thị và nông dân."),
        numberedPoint(2, "Tích hợp đa ngành là xu hướng tất yếu: Một hệ thống thành công cần kết hợp kiến trúc từ blockchain, IoT, mobile, đô thị học và nông nghiệp."),
        numberedPoint(3, "Hợp tác xã và nông dân sẵn sàng cho chuyển đổi số: Qua khảo sát, nhiều hợp tác xã mong muốn có kênh phân phối trực tiếp, minh bạch."),
        numberedPoint(4, "Thành phố thông minh bắt đầu từ những dịch vụ nhỏ: Máy bán hàng là một ví dụ về cách công nghệ có thể cải thiện cuộc sống đô thị hàng ngày."),
        numberedPoint(5, "Pháp lý và công nghệ phải song hành: Để triển khai thực tế, cần khung pháp lý rõ ràng cho thanh toán crypto và bán lẻ tự động."),

        // ── REFERENCES ──
        pageBreak(),
        heading("TÀI LIỆU THAM KHẢO", HeadingLevel.HEADING_1),
        emptyLine(),
        p("[1] S. Shukla, M. Younas, et al., Blockchain Technology: From Theory to Practice. Springer, 2022."),
        p("[2] A. M. Antonopoulos and G. Wood, Mastering Ethereum. O'Reilly Media, 2018."),
        p("[3] V. Buterin, \"Ethereum: A Next-Generation Smart Contract and Decentralized Application Platform,\" 2014."),
        p("[4] S. Nakamoto, \"Bitcoin: A Peer-to-Peer Electronic Cash System,\" 2008."),
        p("[5] K. Christidis and M. Devetsikiotis, \"Blockchains and Smart Contracts for the Internet of Things,\" IEEE Access, vol. 4, pp. 2292-2303, 2016."),
        p("[6] A. Reyna et al., \"On Blockchain and Its Integration with IoT,\" Future Generation Computer Systems, vol. 88, pp. 173-190, 2018."),
        p("[7] M. A. Khan and K. Salah, \"IoT Security: Review, Blockchain Solutions, and Open Challenges,\" FGCS, vol. 82, pp. 395-411, 2018."),
        p("[8] T. M. Fernández-Caramés and P. Fraga-Lamas, \"A Review on the Use of Blockchain for the Internet of Things,\" IEEE Access, vol. 6, pp. 32979-33001, 2018."),
        p("[9] ISO 37122:2019, \"Sustainable cities and communities — Indicators for smart cities,\" 2019."),
        p("[10] A. Caragliu, C. Del Bo, and P. Nijkamp, \"Smart Cities in Europe,\" Journal of Urban Technology, vol. 18, no. 2, pp. 65-82, 2011."),
        p("[11] World Bank, \"Vietnam: Toward a Safe, Clean, and Resilient Water System,\" 2019."),
        p("[12] Bộ NN&PTNT, \"Đề án Chuyển đổi số ngành Nông nghiệp giai đoạn 2021-2025, định hướng đến 2030,\" 2021."),
        p("[13] Chính phủ Việt Nam, \"Đề án phát triển thanh toán không dùng tiền mặt giai đoạn 2021-2025,\" 2021."),
        p("[14] F. Tian, \"An Agri-food Supply Chain Traceability System for China Based on RFID & Blockchain Technology,\" IEEE ICSSSM, 2016."),
        p("[15] M. P. Caro et al., \"Blockchain-based Traceability in Agri-Food Supply Chain Management,\" Computers and Electronics in Agriculture, 2018."),
        p("[16] Ethereum Foundation, \"Sepolia Testnet,\" ethereum.org, 2024."),
        p("[17] Web3Auth, \"Documentation,\" web3auth.io, 2024."),
        p("[18] Firebase, \"Cloud Firestore Documentation,\" firebase.google.com, 2024."),
        p("[19] Espressif Systems, \"ESP32 Technical Reference Manual,\" espressif.com, 2024."),
        p("[20] Flutter, \"Documentation,\" flutter.dev, 2024."),

        // ── END ──
        pageBreak(),
        emptyLine(), emptyLine(), emptyLine(), emptyLine(),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 }, children: [new TextRun({ text: "--- HẾT ---", font: "Times New Roman", size: 28, bold: true, color: "000000" })] }),
        new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Báo cáo được hoàn thành tại Hà Nội, tháng 6 năm 2026", font: "Times New Roman", size: 26, italics: true, color: "000000" })] }),
      ],
    },
  ],
});

// ── GENERATE FILE ──
const OUTPUT_PATH = "C:\\Users\\ADMIN\\My-project\\vending_machine\\BAO_CAO_SMART_CITY_AGRI.docx";
console.log("⏳ Generating combined report...");
Packer.toBuffer(doc).then((buffer) => {
  fs.writeFileSync(OUTPUT_PATH, buffer);
  console.log(`✅ Report saved to: ${OUTPUT_PATH}`);
  console.log(`📄 File size: ${(buffer.length / 1024).toFixed(1)} KB`);
}).catch((err) => {
  console.error("❌ Error:", err.message);
  process.exit(1);
});
